In [7]:
%load_ext nb_black

The nb_black extension is already loaded. To reload it, use:
  %reload_ext nb_black

In [9]:
import pandas as pd

data = pd.read_csv("./weatherAUS.csv")
data.drop(
    [
        "Date",
        "MinTemp",
        "MaxTemp",
        "Rainfall",
        "Evaporation",
        "Sunshine",
        "WindGustDir",
        "WindGustSpeed",
        "WindDir9am",
        "WindDir3pm",
        "WindSpeed9am",
        "WindSpeed3pm",
        "Humidity9am",
        "Humidity3pm",
        "Pressure9am",
        "Pressure3pm",
        "Cloud9am",
        "Cloud3pm",
        "Temp9am",
        "Temp3pm",
        "RainTomorrow",
    ],
    axis=1,
    inplace=True,
)
data.fillna("No", inplace=True)
data

       Location RainToday
0        Albury        No
1        Albury        No
2        Albury        No
3        Albury        No
4        Albury        No
...         ...       ...
145455    Uluru        No
145456    Uluru        No
145457    Uluru        No
145458    Uluru        No
145459    Uluru        No

[145460 rows x 2 columns]

In [10]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
for col in ["RainToday"]:
    data[col] = lb.fit_transform(data[col])
data

/opt/intel/oneapi/intelpython/latest/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)

       Location  RainToday
0        Albury          0
1        Albury          0
2        Albury          0
3        Albury          0
4        Albury          0
...         ...        ...
145455    Uluru          0
145456    Uluru          0
145457    Uluru          0
145458    Uluru          0
145459    Uluru          0

[145460 rows x 2 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

label_encoder.fit(data["Location"])

for col in ["Location"]:
    data[col] = label_encoder.transform(data[col])

data

        Location  RainToday
0              2          0
1              2          0
2              2          0
3              2          0
4              2          0
...          ...        ...
145455        41          0
145456        41          0
145457        41          0
145458        41          0
145459        41          0

[145460 rows x 2 columns]

In [12]:
x_cols = [x for x in data.columns if x != "RainToday"]

X_data = data[x_cols]
y_data = data["RainToday"]

# c = {}
# for i in data:
#     for j in data[i]:
#         if not c.get(j):
#             c.update({j: 1})
#         else:
#             c[j] += 1

# print(c)
data

        Location  RainToday
0              2          0
1              2          0
2              2          0
3              2          0
4              2          0
...          ...        ...
145455        41          0
145456        41          0
145457        41          0
145458        41          0
145459        41          0

[145460 rows x 2 columns]

In [13]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)

knn = knn.fit(X_data, y_data)

y_pred = knn.predict(X_data)

In [14]:
def accuracy(real, predict):
    return sum(y_data == y_pred) / float(real.shape[0])

In [15]:
knn = KNeighborsClassifier(n_neighbors=5, weights="distance")

knn = knn.fit(X_data, y_data)

y_pred = knn.predict(X_data)

print(accuracy(y_data, y_pred))

0.7723360373985976